feat: Onboarding Setup
stacksjs/stacks pull request #956
Opened 2024-03-07 01:17 UTC by dorelljames

Fixes issue #850

2024-04-04 00:46 UTC, dorelljames commented
This should be good to go unless there are still files that I've missed.

2024-04-09 19:41 UTC, chrisbbreuer commented
getting there 🔥

2024-06-29 12:16 UTC, chrisbbreuer requested changes

2024-06-29 12:16 UTC, chrisbbreuer commented on storage/framework/onboarding/index.ts
> +          initialValues: ['prettier', 'eslint'],
Unsure why prettier is here. We don't use it, and actively suggest people not to use it in combination with Stacks formatting 👍

2024-06-29 12:16 UTC, chrisbbreuer commented on storage/framework/core/buddy/src/commands/setup.ts
> +    }
Need to finish this

2024-06-29 12:16 UTC, chrisbbreuer commented on storage/framework/onboarding/package.json
> +}
This shouldn't be here and extracted to core packages, placed where appropriate, like the cli package.

We may already may require these deps elsewhere too

2024-06-29 12:16 UTC, chrisbbreuer commented on storage/framework/onboarding/tsconfig.json
> +}
This also isn't needed then

2025-10-16 09:34 UTC, closed without merging